handler: src/loans/get_loan/handler.lambda_handler
description: Gets a single loan by ID
events:
  - http:
      path: loans/{loan_id}
      method: get
      authorizer:
        type: COGNITO_USER_POOLS
        authorizerId: !Ref ApiGatewayAuthorizer
